name: Build and Test
on: [push]

jobs:
  build:    
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    
    - name: Check Out Code
      uses: actions/checkout@v1

    - name: Lint Code
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        golint -set_exit_status ./src/...

    - name: Restore Dependencies
      run: |        
        go get -v -t -d ./src/...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi        

    - name: Build Code
      run: |        
        go build -v ./src/...
    
    - name: Run Tests
      run: |        
        go test ./src/...    
